### ISSUE TITLE
Hi there, is this still live?

### ISSUE THREAD

**Issue by InfiniFlix** [jafrewa/kisscartoon#21] opened 2017-07-04 22:43 UTC
I installed this but cannot seem to get it to scrape Kiss Cartoon

**Comment by jvonhoff** [comment] 2017-08-15 17:19
See issue #18 .  Until that is fixed, nothing will scrape.

**Comment by InfiniFlix** [comment] 2017-08-15 19:09
Many thanks for the update.

**Comment by jvonhoff** [comment] 2017-08-15 19:13
You bet.  I'm closing this as a duplicate of #18

**Closed by jvonhoff** 2017-08-15 19:13 UTC

**Comment by InfiniFlix** [comment] 2017-08-15 19:17
thx!
